### ISSUE TITLE
Adicionar o README do projeto de acordo com o modelo-projeto-ppo

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/petshop#10]
Vocês devem adicionar um `README.md` na raiz do projeto de vocês, de acordo com esse arquivo [aqui](https://github.com/ifpe-cti/modelo-projeto-ppo/blob/master/README.md), preenchendo cada seção do mesmo de acordo com o projeto de vocês.

**Comment by DanielCalado** [comment]
@fabriciofx, `README.md` adicionado [aqui](https://github.com/ifpe-cti/petshop/blob/master/README.md).
