### ISSUE TITLE
Escolher uma licença para o projeto

### ISSUE THREAD

**Issue by fabriciofx** [ifpe-cti/petshop#11]
Vocês devem escolher uma licença para o código fonte do projeto de vocês. Depois de escolher, criar um arquivo `LICENSE.txt` com essa licença e colocar na raiz do projeto de vocês, que nem foi feito [aqui](https://github.com/fabriciofx/rockpaperscissors/blob/master/LICENSE.txt).

**Comment by DanielCalado** [comment]
@fabriciofx, licença escolhida foi a MIT [aqui](https://github.com/ifpe-cti/petshop/blob/master/LICENSE).
