### ISSUE TITLE
Dúvida sobre como contribuir

### ISSUE THREAD

**Issue by DanielCalado** [ifpe-cti/petshop#12]
@fabriciofx  professor estou com dúvidas no branch e no pull requests, @wemersonifpe enviou so a classe endereço, são quatro classes  cliente, endereço, serviço e agendamento. Pode se enviar as quatro de uma vez ou tem que fazer o procedimento pra cada uma?

**Comment by fabriciofx** [comment]
@DanielCalado Isso depende. A regra de ouro é: **uma issue por funcionalidade**. Assim, se ele quiser permitir o cadastro de clientes no sistema, e para isso precisar de umas 3 classes, tudo bem. No entanto, uma ressalva. Se essa funcionalidade for muito grande, implicar em várias classes, é melhor quebrá-la em outras menores.
No seu caso específico acima, *acho* que seria uma issue para cliente e endereço, outra pra serviço e outra para pagamento.

**Comment by DanielCalado** [comment]
@fabriciofx obrigado professor, estamos nos acostumado com as issue e com o processo de contribuir, mais deu pra entender como deve ser feito.

**Comment by fabriciofx** [comment]
@DanielCalado normal. Leva um tempo para se acostumar mesmo. Tem que ter paciência... Inclusive, [já tem uma issue](https://github.com/ifpe-cti/modelo-projeto-ppo/issues/5) aberta sobre isso.

Se sua dúvida foi sanada, não esqueça de fechar essa issue.
