### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by izaquiel7** [ifpe-cti/petshop#2]

**Comment by fabriciofx** [comment]
@izaquiel7 Você precisa especificar o que vai fazer na issue. Detalhe mais. Do que se trata a issue? Quais casos de uso? Não seria melhor fazer uma issue para cada Caso de uso?

**Comment by izaquiel7** [comment]
Pq uma issue pra cada caso de uso? Esses casos de uso estão representando
as funcionalidades do sistema.

**Comment by fabriciofx** [comment]
@izaquiel7 Não disse que precisava fazer uma issue para cada caso de uso. Perguntei: * Não seria melhor fazer uma issue para cada Caso de uso?*, pois não sei do que se trata e o que será feito. Pode ser que uma issue resolva o problema. Pode ser que não. Cada Caso de Uso irá gerar alguma discussão? Você acha que não tem problema as discussões de todos os Casos de Uso estarem no mesmo lugar? São pontos a serem considerados.

Ademais, se você estiver se referindo a alguma pessoa em específico aqui nas issues, favor citar a pessoa "@login-no-github", como eu fiz agora, com você.

**Comment by izaquiel7** [comment]
Certo, agradeço!

**Comment by fabriciofx** [comment]
@izaquiel7 Estou achando que você não entendeu esta parte:
> Ademais, se você estiver se referindo a alguma pessoa em específico aqui nas issues, favor citar a pessoa "@login-no-github", como eu fiz agora, com você.

**Comment by izaquiel7** [comment]
@fabriciofx ainda to me acostumando com as issues!

**Comment by fabriciofx** [comment]
@izaquiel7 Normal! Agora gostei... aprendeu! 😄

**Comment by fabriciofx** [comment]
@izaquiel7 Tu viu se no comando `mvn package` está tudo funcionando?

O que você acha desse código?

```java
public class A {
   void m();
}
```

**Comment by izaquiel7** [comment]
Vou fechar essa issue por não ter sentido, e enviei um documento de requisitos na issue #3.
