### ISSUE TITLE
Enviando documento de requisitos

### ISSUE THREAD

**Issue by izaquiel7** [ifpe-cti/petshop#3]
# Documento de Requisitos
## PetShop

 
*Daniel Da Silva Calado*
*Izaquiel Cavalcante Da Silva*
*Kaio Brasil*
*Wemerson Diogenes Da Silva*

### Resumo:
O sistema de agendamentos pet shop deverá proporcionar facilidades ao usuário, sendo ele o cliente ou o funcionário.  Contendo funcionalidades como agendamentos para consulta com veterinário, estádia, tosa, banho e vacinação de pets.

### Cliente:
•	**Cadastrar**: Para cadastrar o cliente é necessário informar seu nome, CPF, data nascimento, e-mail, senha.
Prioridade: Essencial  >>Importante Desejável

•	**Faz Login**: Para o cliente fazer login no sistema é necessário informar seu e-mail e senha.
Prioridade: Essencial  >>Importante Desejável
 
•	**Pesquisar Serviços/Preços**: O cliente informa o nome do serviço ou preço e será filtrado uma lista com os serviços ou preços pesquisados.
Prioridade: Essencial  >>Importante Desejável

•	**Visualizar Serviços/Preços**: O cliente ao entrar no sistema pode visualizar os serviços disponíveis e seus preços.
Prioridade: >>Essencial  Importante Desejável

•	**Faz agendamento**: O cliente escolhe o serviço e agenda, mas antes terá que fazer login, se cadastrado.
Prioridade: >>Essencial  Importante Desejável

•	**Visualizar status**: O status do serviço prestado ao seu pet, se já terminou, em andamento ou espera.

### Funcionário:

•	**Crud de serviços e preços**: O funcionário insere, altera, visualiza e/ou deleta todas as informações sobre o serviço.
Prioridade: >>Essencial  Importante Desejável

•	**Visualizar agendamentos**: O funcionário poderá visualizar todos os agendamentos.

•	**Emitir status de  @serviço**: Ao emitir este status o funcionário está indicando que o serviço está em andamento, espera ou se terminou.

**Comment by izaquiel7** [comment]
Por favor, Se acharem alguma irregularidade neste documento, ou se precisar de uma atualização me avisem.

**Comment by izaquiel7** [comment]
@DanielCalado Se achar que o documento está otimo, feche a issue. 👍

**Comment by fabriciofx** [comment]
@izaquiel7 Se este *Documento de Requisitos* é um documento, ele não deve ser escrito aqui na issue. Escreva ele como um documento Markdown e submeta ele como um Pull Request (PR) para que outros possam revisá-lo e fazer comentários em cima dele.

**Note** que você deverá fazer o mesmo procedimento de fork, submeter e etc, igual aos outros, mas tome cuidado para não enviá-lo para o repositório de ifpe-cti/petshop, pois você tem permissão de escrita nesse repositório.

**Comment by DanielCalado** [comment]
@Izaquiel7 pra mim ta bom, faça o que o professor  aconselhou então depois feche a issue.

**Comment by fabriciofx** [comment]
@izaquiel7 Se todos já aprovaram, então você poderia submeter diretamente... você é quem decide.

**Comment by fabriciofx** [comment]
@izaquiel7 Pode ser no formato que você quiser, mas eu recomendo no formato Markdown. Até porque, dependendo do formato que você vai enviar, como você vai versionar *dentro* do documento. E formato Markdown não tem o que fazer. Você mesmo, nessa mesma issue, já submeteu nesse formato, não? E ficou muito bom!
