### ISSUE TITLE
Criar classe Endereço

### ISSUE THREAD

**Issue by wemersonifpe** [ifpe-cti/petshop#5]
Issues aberta para criação da classe endereço, a qual sera utilizada como atributo composto da classe Cliente, ainda à ser criada.

**Comment by izaquiel7** [comment]
@wemersonifpe Por que implementar uma classe Endereco? quero dizer, por que saber o endereço do Cliente?

**Comment by DanielCalado** [comment]
@izaquiel7  o sistema tem funcionalidades como agendamentos para consulta com veterinário, estádia, tosa, banho e vacinação de pets.
Ou seja o animal vai ficar no estabelecimento para ser feito tais serviço. Se o dono nao  buscar o animal, simplesmente abandonar ele no local  a empresa faz o que se nao sebe onde ele mora?

**Comment by fabriciofx** [comment]
@izaquiel7 Normalmente os petshops possuem um serviço de ir buscar e devolver os pets na casa do dono. Sem o endereço, como o petshop pode oferecer esse serviço? 😃

**Comment by wemersonifpe** [comment]
@izaquiel7 Desculpa a demora a responder, mas os motivos são realmente esses como Daniel e Fabricio falaram, alem disso a classe Endereço não sera apenas utilizada por cliente ela também sera necessária para saber a localização do petshop onde o cliente ira deixar seu e buscar seu pet.

**Comment by fabriciofx** [comment]
@wemersonifpe Acho que não entendi direito qual é a ideia dessa classe `Endereco`:
> alem disso a classe Endereço não sera apenas utilizada por cliente ela também sera necessária para saber a localização do petshop onde o cliente ira deixar seu e buscar seu pet.
Você não precisa de uma classe `Endereco` para isto. A ideia de uma classe `Endereco` seria para armazenar o endereço de um cliente, um fornecedor... coisas deste gênero. A não ser que eu não tenha entendido qual o objetivo dessa classe `Endereco`...

**Comment by wemersonifpe** [comment]
@fabriciofx  Sim, o objetivo da classe endereço é apenas este, armazenar o endereço de clientes e fornecedores.

**Comment by fabriciofx** [comment]
@wemersonifpe Certo, mas não vi isso no PR que você submeteu. A classe apenas está guardando em memória...
