### ISSUE TITLE
Testes de software

### ISSUE THREAD

**Issue by DanielCalado** [ifpe-cti/petshop#7]
@fabriciofx essas classes precisão de testes ou podem sem enviadas para o repositório sem testes?

```java
public class Servico{
private int id;
private String nome;
private int tempo;
private BigDecimal preco;
private List <Date> datasDisponiveis;
}
```
```java
Public class Argendamento {
private int id;
private Cliente cliente;
private List <Servico> servico;
private BigDecimal precoTotal;
}
```

**Comment by fabriciofx** [comment]
@DanielCalado Pode porque não há nenhuma ferramenta ou semelhante que impeça de você submeter código sem que haja os respectivos testes. Mas o ideal é que você enviasse também os testes...
